version: '3.9'

services:

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
      - celery
    volumes:
      - ./service:/service
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    hostname: redis

  celery:
    container_name: celery
    build: .
    command: "celery -A celery_app.app worker --loglevel=info"
    volumes:
      - ./service:/service
    depends_on:
      - redis

  flower:
    container_name: flower
    build:
      context: .
    hostname: flower
    ports:
      - "5555:5555"
    command: "celery -A celery_app.app flower"
    depends_on:
      - redis

volumes:
  data:
