version: '3'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - db:/root/db
    depends_on:
      - sqlite3

  sqlite3:
    image: nouchka/sqlite3:latest
    command:
      - entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - db:/root/db

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  celery:
    build: .
    command: "celery -A celery_app.app worker --loglevel=info"
    depends_on:
      - app
      - redis
      - sqlite3

  flower:
    build:
      context: .
    hostname: flower
    ports:
      - "5555:5555"
    command: "celery -A celery_app.app flower"
    volumes:
      - db:/root/db
    depends_on:
      - celery

volumes:
  db:
