version: '3.9'

services:

  db:
    image: postgres:15
    container_name: db
    volumes:
      - /.pg/data/db:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    depends_on:
      - db
    volumes:
      - ./service:/service
    env_file:
      - .env

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    hostname: redis

  celery:
    container_name: celery
    build: .
    command: "celery -A mytest.celery_app.app worker --loglevel=info"
    volumes:
      - ./service:/service
    depends_on:
      - redis

  flower:
    container_name: flower
    build:
      context: .
    hostname: flower
    ports:
      - "5555:5555"
    command: "celery -A mytest.celery_app.app flower"
    depends_on:
      - redis
