version: '3'

volumes:
  db:

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    command:
      - entrypoint.sh
    stdin_open: true
    tty: true
    volumes:
      - db:/root/db

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - db:/root/db
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: "celery -A mytest worker -l info"
    depends_on:
      - app

  flower:
    build:
      context: .
    hostname: flower
    ports:
      - "5555:5555"
    command: "celery -A mytest flower"
    volumes:
      - db:/root/db
    depends_on:
      - redis