# Generated by Django 4.2.6 on 2023-10-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='Выбери файл',
        ),
    ]
