# Generated by Django 4.2.6 on 2023-10-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_rename_выбери_файл_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='processed',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Выбери файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
